"""create core tables

Revision ID: 8db92fe3d036
Revises: 
Create Date: 2026-09-03 00:43:36.665574

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8db92fe3d036'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('name', name=op.f('uq_tenants_name'))
    )
    op.create_table('lead_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('external_event_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('telegram', 'website', 'avito', name='leadsource', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('consent_status', sa.Enum('unknown', 'opt_in', 'opt_out', name='consentstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('new', 'qualified', 'draft_ready', 'awaiting_approval', 'approved', 'crm_synced', 'manual_review', 'opt_out', 'dead_letter', name='casestatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('manual_review_reason', sa.Text(), nullable=True),
    sa.Column('follow_up_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_lead_cases_tenant_id_tenants'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_cases')),
    sa.UniqueConstraint('tenant_id', 'external_event_id', name='uq_lead_cases_external_event_id')
    )
    op.create_table('lead_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('telegram', 'website', 'avito', name='leadsource', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('external_event_id', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.Enum('accepted', 'duplicate', 'invalid', name='eventoutcome', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_lead_events_tenant_id_tenants'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_events')),
    sa.UniqueConstraint('tenant_id', 'external_event_id', name='uq_lead_events_external_event_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['lead_cases.id'], name='fk_audit_log_case_id_lead_cases'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('crm_sync_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'dead_letter', name='syncstatus', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('crm_deal_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['lead_cases.id'], name='fk_crm_sync_jobs_case_id_lead_cases'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crm_sync_jobs')),
    sa.UniqueConstraint('case_id', name=op.f('uq_crm_sync_jobs_case_id')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_crm_sync_jobs_idempotency_key'))
    )
    op.create_table('drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('clarifying_question', sa.Text(), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=False),
    sa.Column('guardrail_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['lead_cases.id'], name='fk_drafts_case_id_lead_cases'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drafts')),
    sa.UniqueConstraint('case_id', name=op.f('uq_drafts_case_id'))
    )
    op.create_table('qualifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('need', sa.Text(), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'medium', 'high', name='urgency', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_explicit', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('manual_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_qualifications_confidence_range')),
    sa.CheckConstraint('quality_score BETWEEN 0 AND 100', name=op.f('ck_qualifications_quality_score_range')),
    sa.ForeignKeyConstraint(['case_id'], ['lead_cases.id'], name='fk_qualifications_case_id_lead_cases'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualifications')),
    sa.UniqueConstraint('case_id', name=op.f('uq_qualifications_case_id'))
    )

    # Демо-арендатор AthenAI DemoService — вымышленная компания из задания,
    # синтетический UUID, никаких реальных данных.
    op.execute(
        "INSERT INTO tenants (id, name, config, is_active) "
        "VALUES ('11111111-1111-4111-8111-111111111111', "
        "'athenai_demoservice', '{}', true)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualifications')
    op.drop_table('drafts')
    op.drop_table('crm_sync_jobs')
    op.drop_table('audit_log')
    op.drop_table('lead_events')
    op.drop_table('lead_cases')
    op.drop_table('tenants')
    # ### end Alembic commands ###
