"""journal may store duplicate delivery attempts

Revision ID: bbb80df6fbf8
Revises: 8db92fe3d036
Create Date: 2026-09-03 01:22:43.261760

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'bbb80df6fbf8'
down_revision: str | None = '8db92fe3d036'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_crm_sync_jobs_syncstatus'), 'crm_sync_jobs', type_='check')
    op.drop_constraint(op.f('ck_lead_cases_casestatus'), 'lead_cases', type_='check')
    op.drop_constraint(op.f('ck_lead_cases_consentstatus'), 'lead_cases', type_='check')
    op.drop_constraint(op.f('ck_lead_cases_leadsource'), 'lead_cases', type_='check')
    op.drop_constraint(op.f('uq_lead_events_external_event_id'), 'lead_events', type_='unique')
    op.drop_constraint(op.f('ck_lead_events_eventoutcome'), 'lead_events', type_='check')
    op.drop_constraint(op.f('ck_lead_events_leadsource'), 'lead_events', type_='check')
    op.drop_constraint(op.f('ck_qualifications_urgency'), 'qualifications', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_qualifications_urgency'), 'qualifications', "urgency::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_lead_events_leadsource'), 'lead_events', "source::text = ANY (ARRAY['telegram'::character varying, 'website'::character varying, 'avito'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_lead_events_eventoutcome'), 'lead_events', "outcome::text = ANY (ARRAY['accepted'::character varying, 'duplicate'::character varying, 'invalid'::character varying]::text[])")
    op.create_unique_constraint(op.f('uq_lead_events_external_event_id'), 'lead_events', ['tenant_id', 'external_event_id'], postgresql_nulls_not_distinct=False)
    op.create_check_constraint(op.f('ck_lead_cases_leadsource'), 'lead_cases', "source::text = ANY (ARRAY['telegram'::character varying, 'website'::character varying, 'avito'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_lead_cases_consentstatus'), 'lead_cases', "consent_status::text = ANY (ARRAY['unknown'::character varying, 'opt_in'::character varying, 'opt_out'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_lead_cases_casestatus'), 'lead_cases', "status::text = ANY (ARRAY['new'::character varying, 'qualified'::character varying, 'draft_ready'::character varying, 'awaiting_approval'::character varying, 'approved'::character varying, 'crm_synced'::character varying, 'manual_review'::character varying, 'opt_out'::character varying, 'dead_letter'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_crm_sync_jobs_syncstatus'), 'crm_sync_jobs', "status::text = ANY (ARRAY['pending'::character varying, 'succeeded'::character varying, 'dead_letter'::character varying]::text[])")
    # ### end Alembic commands ###
